apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-kubernetes-v1
spec:
  selector:
    matchLabels:
      app: angular-kubernetes-v1
  replicas: 3
  template:
    metadata:
      labels:
        app: angular-kubernetes-v1
    spec:
      containers:
        - name: angular-kubernetes-v1
          image: ramisistemas/frontendinmobiliaria:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4200